name: video-optimizer
base: core22
version: "0.1.2"
summary: Easily optimize and convert your videos
description: |
  Video Optimizer is a modern desktop application to conver and update the metadas of your video files. It features a modern interface, supports many formats, manages audio and subtitle tracks. It's build with ffmpeg-next.
grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

architectures:
  - amd64

apps:
  video-optimizer:
    command: bin/video-optimizer
    desktop: usr/share/applications/video-optimizer.desktop
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - audio-playback
      - removable-media

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu
parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu
      npm installcd 
      npm run tauri build -- --bundles deb
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=video-optimizer|Icon=/usr/share/icons/hicolor/32x32/apps/video-optimizer.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/video-optimizer.desktop
