name: video-optimizer
base: core24
version: '1.0.0'
compression: lzo
summary: A powerful video converter and optimizer.
description: |
  Video Optimizer is a modern, high-performance tool for converting and optimizing videos.
  It supports hardware acceleration, smart renaming, and metadata management.
title: Video Optimizer
contact: https://github.com/kroenen/video-optimizer
license: MIT
website: https://github.com/kroenen/video-optimizer
source-code: https://github.com/kroenen/video-optimizer
issues: https://github.com/kroenen/video-optimizer/issues

icon: snap/gui/video-optimizer.png

grade: stable
confinement: strict

apps:
  video-optimizer:
    command: usr/bin/video-optimizer
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - network
      - opengl
      - audio-playback
    environment:
      # Ensure we use the correct library paths if needed
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"

parts:
  video-optimizer:
    plugin: dump
    # Point this to the .deb generated by 'npm run tauri build'
    # You might need to adjust the path depending on where you run snapcraft from
    source: "src-tauri/target/release/bundle/deb/video-optimizer_1.0.0_amd64.deb"
    source-type: deb
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
      - libssl3
      - ffmpeg # Include ffmpeg in the snap